# Generated by Django 5.2.7 on 2025-12-08 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('current_status_id', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('low', 'LOW'), ('normal', 'NORMAL'), ('high', 'HIGH')], max_length=6)),
                ('type', models.CharField(choices=[('infrastructure', 'INFRASTRUCTURE'), ('safety', 'SAFETY'), ('environment', 'ENVIRONMENT'), ('other', 'OTHER')], max_length=14)),
                ('assigned_unit', models.CharField(choices=[('maintenance', 'MAINTENANCE'), ('police', 'POLICE'), ('environmental', 'ENVIRONMENTAL'), ('general', 'GENERAL')], max_length=13)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
