# Generated by Django 5.2.7 on 2025-12-08 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='current_status_id',
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('new', 'NEW'), ('in_progress', 'IN_PROGRESS'), ('resolved', 'RESOLVED'), ('rejected', 'REJECTED')], max_length=11)),
                ('moderator_comment', models.TextField(blank=True, null=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.report')),
            ],
        ),
    ]
