# Generated by Django 5.2.7 on 2026-01-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_report_location_report_latitude_and_more'),
        ('api', '0006_comment'),
    ]

    operations = [
    ]
